version: '3.4'

services:
  ab-inbev.services.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ABINBEVDB;User Id=sa;Password=YourPassword123!;TrustServerCertificate=true
    ports:
      - "5000:5000"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    depends_on:
      - sqlserver

  migrations-infra-data:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - .:/src
    working_dir: /src/src/AB-INBEV.Infra.Data
    command: /bin/sh -c "dotnet tool install --global dotnet-ef && export PATH=\"$PATH:/root/.dotnet/tools\" && dotnet ef database update"
    depends_on:
      - sqlserver

  migrations-crosscutting-identity:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - .:/src
    working_dir: /src/src/AB-INBEV.CrossCutting.Identity
    command: /bin/sh -c "dotnet tool install --global dotnet-ef && export PATH=\"$PATH:/root/.dotnet/tools\" && dotnet ef database update"
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: YourPassword123!
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata: